insert into npets values (NULL, 'Milo', 'Chien', 'Berger Allemand', 20, 2, 1000, 'Mâle');
insert into npets values (NULL, 'Patty', 'Chien', 'Bouvier Bernois', 30, 4, 2000, 'Femelle');
insert into npets values (NULL, 'Bella', 'Chien', 'Chihuahua', 5, 1, 500, 'Femelle');
insert into npets values (NULL, 'Tiger', 'Chat', 'Siamois', 5, 2, 500, 'Mâle');
insert into npets values (NULL, 'Luna', 'Chat', 'Siamois', 5, 2, 500, 'Femelle');
insert into npets values (NULL, 'Nala', 'monkey', 'baboon', 34.0, 2, 8700, 'female');
insert into npets values (NULL, 'Coco', 'monkey', 'baboon', 34.0, 2, 5000, 'male');
insert into npets values (NULL, 'Lola', 'monkey', 'baboon', 34.0, 2, 7000, 'female');
insert into npets values (NULL, 'Felix', 'tiger', 'malaysia', 105.3, 7, 80000, 'male');
insert into npets values (NULL, 'Leo', 'tiger', 'malaysia', 105.3, 5, 100000, 'male');