insert into pets values ('Milo', 'Chien', 'Berger Allemand', 20, 2, 1000, 'Mâle');
insert into pets values ('Patty', 'Chien', 'Bouvier Bernois', 30, 4, 2000, 'Femelle');
insert into pets values ('Bella', 'Chien', 'Chihuahua', 5, 1, 500, 'Femelle');
insert into pets values ('Tiger', 'Chat', 'Siamois', 5, 2, 500, 'Mâle');
insert into pets values ('Luna', 'Chat', 'Siamois', 5, 2, 500, 'Femelle');
insert into pets values ('Nala', 'monkey', 'baboon', 34.0, 2, 8700, 'female');
insert into pets values ('Coco', 'monkey', 'baboon', 34.0, 2, 5000, 'male');
insert into pets values ('Lola', 'monkey', 'baboon', 34.0, 2, 7000, 'female');
insert into pets values ('Felix', 'tiger', 'malaysia', 105.3, 7, 80000, 'male');
insert into pets values ('Leo', 'tiger', 'malaysia', 105.3, 5, 100000, 'male');
